import { RequestAuthorizationSequence } from "./requestAuthorizationSequence";

export enum authorizationActionsIdentifier {
    REQUEST_AUTHORIZATION_SEQUENCE = "REQUEST_AUTHORIZATION_SEQUENCE",
    SUCCESS_REQUEST_AUTHORIZATION_SEQUENCE = "SUCCESS_REQUEST_AUTHORIZATION_SEQUENCE",
    FAILED_REQUEST_AUTHORIZATION_SEQUENCE = "FAILED_REQUEST_AUTHORIZATION_SEQUENCE",
    REQUEST_CODE_ACTIVATE = "REQUEST_CODE_ACTIVATE",
    SUCCESS_REQUEST_CODE_ACTIVATE = "SUCCESS_REQUEST_CODE_ACTIVATE",
    FAILED_REQUEST_CODE_ACTIVATE = "FAILED_REQUEST_CODE_ACTIVATE",
}

export type authorizationActions = RequestAuthorizationSequence;
