import { RequestAuthorizationSequence } from "./requestAuthorizationSequence";

export enum authorizationActionsIdentifier {
    REQUEST_AUTHORIZATION_SEQUENCE = "REQUEST_AUTHORIZATION_SEQUENCE",
    SUCCESS_REQUEST_AUTHORIZATION_SEQUENCE = "SUCCESS_REQUEST_AUTHORIZATION_SEQUENCE",
    FAILED_REQUEST_AUTHORIZATION_SEQUENCE = "FAILED_REQUEST_AUTHORIZATION_SEQUENCE",
    REQUEST_CODE_AUTHORIZATION = "REQUEST_CODE_AUTHORIZATION",
    SUCCESS_REQUEST_CODE_AUTHORIZATION = "SUCCESS_REQUEST_CODE_AUTHORIZATION",
    FAILED_REQUEST_CODE_AUTHORIZATION = "FAILED_REQUEST_CODE_AUTHORIZATION",
}

export type authorizationActions = RequestAuthorizationSequence;
