language: node_js
node_js:
    - "10"
cache:
    yarn: true
    directories:
        - node_modules
# https://stackoverflow.com/questions/15674064/how-to-fix-a-permission-denied-publickey-error-for-a-git-submodule-update-in-t/24600210
git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install:
    - yarn
script:
    - echo "nothing!"
before_deploy:
    - yarn run build-storybook
deploy:
    provider: pages
    local-dir: "storybook-static"
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
        branch: master
