version: 2.1
references:
    workspace_root: &workspace_root
                        /tmp/workspace
    attach_workspace: &attach_workspace
        attach_workspace:
            at: *workspace_root
executors:
    my-executor:
        docker:
            - image: node:12.18.0-stretch
        working_directory: *workspace_root
jobs:
    install:
        executor: my-executor
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                    - v{{ .Environment.CIRCLE_CACHE_VERSION }}-node-module-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                    - v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-lock-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                    - v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
                    - v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-cache-master-{{ .Environment.CIRCLE_JOB }}
            - run:
                name: Install Dependencies
                command: yarn install
            - save_cache:
                name: Save node_modules Cache
                key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-node-module-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules
            - save_cache:
                name: Save Yarn Package Cache
                key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - persist_to_workspace:
                root: *workspace_root
                paths:
                    - ./
    test:
        executor: my-executor
        steps:
            - *attach_workspace
            - run:
                name: test
                command: yarn test
    security-check:
        executor: my-executor
        steps:
            - *attach_workspace
            - run:
                name: synk-check
                command: yarn snyk-protect
workflows:
    version: 2
    build_and_test:
        jobs:
            - install
            - test:
                requires:
                    - install
            - security-check:
                requires:
                    - install
