version: 2.1
executors:
    my-executor:
        docker:
            - image: node/12.18.0-stretch
        working_directory: /
jobs:
    install:
        executor: my-executor
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --immutable
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - persist_to_workspace:
                root: workspace
                paths:
                    - /
    test:
        executor: my-executor
        steps:
            - attach_workspace:
                at: /
            - run:
                name: hoge
                command: ls -l
            - run:
                name: test
                command: yarn test
    security-check:
        executor: my-executor
        steps:
            - attach_workspace:
                  at: /
            - run:
                name: synk-check
                command: yarn snyk-protect
workflows:
    version: 2
    build_and_test:
        jobs:
            - install
            - test:
                requires:
                    - install
            - security-check:
                requires:
                    - install
