version: 2.1
orbs:
    node: circleci/node@3.0.0
jobs:
    install:
        docker:
            - image: node:latest
        working_directory: ~/Tempest-Client
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --immutable
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
    test:
        docker:
            - image: node:latest
        working_directory: ~/Tempest-Client
        steps:
            - run:
                name: test
                command: yarn test
    security-check:
        docker:
            - image: node:latest
        working_directory: ~/Tempest-Client
        steps:
            - run:
                name: synk-check
                command: yarn snyk-protect
workflows:
    version: 2
    build_and_test:
        jobs:
            - install
            - test:
                requires:
                    - install
            - security-check:
                requires:
                    - install
